import type { BankSignature } from './types';

// Header patterns below assume lower-cased + trimmed headers (see ingestFile).
export const ALL_SIGNATURES: BankSignature[] = [
  {
    id: 'sparkasse.generic',
    family: 'GermanLegacy',
    displayName: 'Sparkasse (Finanz Informatik)',
    headerMatchers: [
      { pattern: /auftragskonto|kontonummer/, weight: 3 },
      { pattern: /buchungstag|buchungsdatum/, weight: 3 },
      { pattern: /valutadatum|wertstellung/, weight: 3 },
      { pattern: /buchungstext/, weight: 2 },
      { pattern: /verwendungszweck|verwendungszwecke/, weight: 2 },
      { pattern: /begu[eü]nstigter\/zahlungspflichtiger/, weight: 4 },
      { pattern: /betrag/, weight: 3 },
      { pattern: /w(ä|ae)hrung/, weight: 2 },
    ],
    dateFormat: 'dd.MM.yy',
    numberFormat: 'commaDecimal',
    delimiterHint: ';',
    encodingHint: 'latin1',
  },
  {
    id: 'vrbank.legacy',
    family: 'GermanLegacy',
    displayName: 'Volksbank / Postbank CSV',
    headerMatchers: [
      { pattern: /buchungs?tag|buchungs?datum/, weight: 3 },
      { pattern: /wertstellung|valuta/, weight: 3 },
      { pattern: /umsatz.*eur|betrag/, weight: 4 },
      { pattern: /buchungstext|umsatzart/, weight: 3 },
      { pattern: /auftraggeber|empfaenger|beguenstigter/, weight: 2 },
    ],
    dateFormat: 'dd.MM.yyyy',
    numberFormat: 'commaDecimal',
    delimiterHint: ';',
    encodingHint: 'latin1',
  },
  {
    id: 'comdirect.giro',
    family: 'GermanLegacy',
    displayName: 'comdirect Girokonto',
    headerMatchers: [
      { pattern: /buchungstag/, weight: 4 },
      { pattern: /wertstellung/, weight: 3 },
      { pattern: /vorgang/, weight: 3 },
      { pattern: /buchungstext/, weight: 3 },
      { pattern: /umsatz.*eur/, weight: 4 },
    ],
    dateFormat: 'dd.MM.yyyy',
    numberFormat: 'commaDecimal',
    delimiterHint: ';',
    encodingHint: 'utf8',
  },
  {
    id: 'n26.standard',
    family: 'Neobank',
    displayName: 'N26',
    headerMatchers: [
      { pattern: /^date$/, weight: 3 },
      { pattern: /^payee$/, weight: 3 },
      { pattern: /transaction type/, weight: 3 },
      { pattern: /payment reference/, weight: 3 },
      { pattern: /^category$/, weight: 2 },
      { pattern: /amount \(eur\)|amount/, weight: 4 },
    ],
    dateFormat: 'yyyy-MM-dd',
    numberFormat: 'dotDecimal',
    delimiterHint: ',',
    encodingHint: 'utf8',
  },
  {
    id: 'revolut.standard',
    family: 'Neobank',
    displayName: 'Revolut',
    headerMatchers: [
      { pattern: /^type$/, weight: 3 },
      { pattern: /^description$/, weight: 3 },
      { pattern: /completed date/, weight: 3 },
      { pattern: /^amount$/, weight: 4 },
      { pattern: /^currency$/, weight: 3 },
      { pattern: /^state$/, weight: 2 },
    ],
    dateFormat: 'yyyy-MM-dd',
    numberFormat: 'dotDecimal',
    delimiterHint: ',',
    encodingHint: 'utf8',
  },
  {
    id: 'bunq.standard',
    family: 'Neobank',
    displayName: 'bunq',
    headerMatchers: [
      { pattern: /^date$/, weight: 3 },
      { pattern: /^amount$/, weight: 4 },
      { pattern: /^account$/, weight: 2 },
      { pattern: /counterparty/, weight: 3 },
      { pattern: /^name$/, weight: 2 },
      { pattern: /^description$/, weight: 3 },
    ],
    dateFormat: 'yyyy-MM-dd',
    numberFormat: 'dotDecimal',
    delimiterHint: ',',
    encodingHint: 'utf8',
  },
  {
    id: 'paypal.de',
    family: 'PayPal',
    displayName: 'PayPal (DE)',
    headerMatchers: [
      { pattern: /^date$/, weight: 3 },
      { pattern: /^time$/, weight: 2 },
      { pattern: /^timezone$/, weight: 1 },
      { pattern: /^name$/, weight: 2 },
      { pattern: /^type$/, weight: 3 },
      { pattern: /^status$/, weight: 2 },
      { pattern: /^gross$/, weight: 4 },
      { pattern: /^fee$/, weight: 3 },
      { pattern: /^net$/, weight: 4 },
      { pattern: /^currency$/, weight: 2 },
    ],
    dateFormat: 'MM/dd/yyyy',
    numberFormat: 'dotDecimal',
    delimiterHint: ',',
    encodingHint: 'utf8',
  },
  {
    id: 'trade_republic.executions',
    family: 'Brokerage',
    displayName: 'Trade Republic Executions',
    headerMatchers: [
      { pattern: /^timestamp|date$/, weight: 3 },
      { pattern: /^isin$/, weight: 4 },
      { pattern: /^ticker$/, weight: 3 },
      { pattern: /type|transaction/, weight: 3 },
      { pattern: /^quantity$/, weight: 3 },
      { pattern: /^amount$/, weight: 4 },
      { pattern: /^currency$/, weight: 2 },
    ],
    dateFormat: 'yyyy-MM-dd',
    numberFormat: 'dotDecimal',
    delimiterHint: ',',
    encodingHint: 'utf8',
  },
];


