version: '3.9'
services:
  db:
    image: postgres:16
    container_name: nimbus-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nimbus
      POSTGRES_PASSWORD: nimbus
      POSTGRES_DB: nimbusdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


