import type { MerchantPattern } from './types';

export const SYSTEM_MERCHANT_PATTERNS: MerchantPattern[] = [
  { id: 'rewe', pattern: 'REWE', normalized: 'REWE', category: 'groceries', score: 200, source: 'system' },
  { id: 'edeka', pattern: 'EDEKA', normalized: 'EDEKA', category: 'groceries', score: 200, source: 'system' },
  { id: 'aldi', pattern: 'ALDI', normalized: 'ALDI', category: 'groceries', score: 180, source: 'system' },
  { id: 'lidl', pattern: 'LIDL', normalized: 'LIDL', category: 'groceries', score: 180, source: 'system' },
  { id: 'dm', pattern: ' DM ', normalized: 'DM DROGERIE', category: 'shopping', score: 180, source: 'system' },
  { id: 'rossmann', pattern: 'ROSSMANN', normalized: 'ROSSMANN', category: 'shopping', score: 180, source: 'system' },
  { id: 'netflix', pattern: 'NETFLIX', normalized: 'NETFLIX', category: 'subscriptions:streaming', score: 220, source: 'system' },
  { id: 'spotify', pattern: 'SPOTIFY', normalized: 'SPOTIFY', category: 'subscriptions:streaming', score: 220, source: 'system' },
  { id: 'disneyplus', pattern: 'DISNEY+', normalized: 'DISNEY PLUS', category: 'subscriptions:streaming', score: 200, source: 'system' },
  { id: 'adobe', pattern: 'ADOBE', normalized: 'ADOBE', category: 'subscriptions:software', score: 180, source: 'system' },
  { id: 'microsoft', pattern: 'MICROSOFT', normalized: 'MICROSOFT', category: 'subscriptions:software', score: 180, source: 'system' },
  { id: 'apple', pattern: 'APPLE.COM/BILL', normalized: 'APPLE', category: 'subscriptions:software', score: 170, source: 'system' },
  { id: 'dbahn', pattern: 'DEUTSCHE BAHN', normalized: 'DEUTSCHE BAHN', category: 'transport:public', score: 210, source: 'system' },
  { id: 'bvg', pattern: ' BVG ', normalized: 'BVG', category: 'transport:public', score: 180, source: 'system' },
  { id: 'sbb', pattern: 'SBB', normalized: 'SCHWEIZERISCHE BAHN', category: 'transport:public', score: 150, source: 'system' },
  { id: 'uber', pattern: 'UBER TRIP', normalized: 'UBER', category: 'transport:rideshare', score: 200, source: 'system' },
  { id: 'uber_eats', pattern: 'UBER EATS', normalized: 'UBER EATS', category: 'dining:delivery', score: 200, source: 'system' },
  { id: 'lieferando', pattern: 'LIEFERANDO', normalized: 'LIEFERANDO', category: 'dining:delivery', score: 200, source: 'system' },
  { id: 'wolt', pattern: 'WOLT', normalized: 'WOLT', category: 'dining:delivery', score: 180, source: 'system' },
  { id: 'paypal', pattern: 'PAYPAL', normalized: 'PAYPAL', score: 120, source: 'system' },
  { id: 'amazon', pattern: 'AMAZON', normalized: 'AMAZON', category: 'shopping', score: 150, source: 'system' },
  { id: 'zalando', pattern: 'ZALANDO', normalized: 'ZALANDO', category: 'shopping', score: 160, source: 'system' },
  { id: 'ikea', pattern: 'IKEA', normalized: 'IKEA', category: 'shopping:home', score: 170, source: 'system' },
  { id: 'shell', pattern: 'SHELL', normalized: 'SHELL', category: 'transport:fuel', score: 170, source: 'system' },
  { 
    id: 'aral_station',
    pattern: 'ARAL STATION',
    normalized: 'ARAL STATION',
    category: 'transport:fuel',
    score: 190,
    source: 'system',
  },
  { id: 'aral', pattern: 'ARAL', normalized: 'ARAL', category: 'transport:fuel', score: 170, source: 'system' },
  // Fast food / dining chains
  {
    id: 'kfc',
    pattern: 'KFC',
    normalized: 'KFC',
    category: 'dining:fast_food',
    score: 190,
    source: 'system',
  },
  {
    id: 'kentucky_fried_chicken',
    pattern: 'KENTUCKY FRIED CHICKEN',
    normalized: 'KENTUCKY FRIED CHICKEN',
    category: 'dining:fast_food',
    score: 190,
    source: 'system',
  },
  // Discount stores
  {
    id: 'action_discount_store',
    pattern: ' ACTION ',
    normalized: 'ACTION',
    category: 'shopping:discount_store',
    score: 180,
    source: 'system',
  },
  // Café / coffee shops - conservative patterns to avoid B2B false positives
  {
    id: 'cafe',
    pattern: ' CAFE ',
    normalized: 'CAFE',
    category: 'dining:cafe',
    score: 150,
    source: 'system',
  },
  {
    id: 'cafe_accent',
    pattern: ' CAFÉ ',
    normalized: 'CAFE',
    category: 'dining:cafe',
    score: 150,
    source: 'system',
  },
  {
    id: 'coffee_shop',
    pattern: ' COFFEE ',
    normalized: 'COFFEE',
    category: 'dining:cafe',
    score: 150,
    source: 'system',
  },
  { id: 'trade_republic', pattern: 'TRADE REPUBLIC', normalized: 'TRADE REPUBLIC', category: 'savings:brokerage', score: 190, source: 'system' },
  { id: 'scalable', pattern: 'SCALABLE', normalized: 'SCALABLE CAPITAL', category: 'savings:brokerage', score: 190, source: 'system' },
  { id: 'klarna', pattern: 'KLARNA', normalized: 'KLARNA', category: 'fees:service', score: 130, source: 'system' },
  { id: 'postbank', pattern: 'POSTBANK', normalized: 'POSTBANK', category: 'fees:bank', score: 150, source: 'system' },
  // Photo booths / entertainment
  {
    id: 'bildwerk_fotoautomat',
    pattern: 'BILDWERK FOTOAUTOMAT',
    normalized: 'BILDWERK_FOTOAUTOMAT',
    category: 'shopping',
    score: 180,
    source: 'system',
  },
  {
    id: 'fotoautomat',
    pattern: ' FOTOAUTOMAT ',
    normalized: 'FOTOAUTOMAT',
    category: 'shopping',
    score: 150,
    source: 'system',
  },
];

